Bump pygobject from 3.50.0 to 3.52.1 + related sacrifices (alternative to broken #2323) (#2325)
* requirements(deps): bump pygobject from 3.50.0 to 3.52.1

Bumps [pygobject](https://pygobject.gnome.org) from 3.50.0 to 3.52.1.

---
updated-dependencies:
- dependency-name: pygobject
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* build-deb.yml: Fix python3-stdeb for Python 3.12

* build-deb.yml: Install unmet dependency build-essential

* build-rpm.yml: Disable fail-fast

* CI: Make bump to pygobject 3.52.1 possible

The bump to Ubuntu "noble" 24.04 is related to the fact
that package libgirepository-2.0-dev just does not exist
in Ubuntu "jammy" 22.04, yet.
https://packages.ubuntu.com/noble/libgirepository-2.0-dev

librsvg2-common is needed for the gdk-pixpuf loader for SVG.

wheel is no longer installed through pip to avoid this symptom:
> ERROR: Cannot uninstall wheel 0.42.0, RECORD file not found.
> Hint: The package was installed by debian.

* build-rpm.yml: Drop broken RPM build for Python 3.9, 3.10, 3.11

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>