CI: Make bump to pygobject 3.52.1 possible
The bump to Ubuntu "noble" 24.04 is related to the fact
that package libgirepository-2.0-dev just does not exist
in Ubuntu "jammy" 22.04, yet.
https://packages.ubuntu.com/noble/libgirepository-2.0-dev

librsvg2-common is needed for the gdk-pixpuf loader for SVG.

wheel is no longer installed through pip to avoid this symptom:
> ERROR: Cannot uninstall wheel 0.42.0, RECORD file not found.
> Hint: The package was installed by debian.